name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[heic,raw]
          pip install -r requirements.txt
          pip install black isort flake8 mypy pytest

      - name: Code quality checks
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy unified_sort || true

      - name: Tests
        run: pytest -q
